import json
from datetime import datetime
from pathlib import Path

from trendlab.domain.models import MarketInsight, Prediction


class ReportGenerator:
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown(
        self, 
        insights: list[MarketInsight], 
        predictions: list[Prediction]
    ) -> Path:
        timestamp = datetime.now().strftime("%Y-%m-%d")
        filename = self.output_dir / f"market_report_{timestamp}.md"
        
        content = [
            "# Crypto Market Intelligence Report",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "## ⚠️ Disclaimer",
            "> **NOT FINANCIAL ADVICE.** This report is generated by an automated ML pipeline for informational purposes only. "  # noqa: E501
            "Crypto assets are highly volatile. Do your own research.",
            "",
            "## 1. Executive Summary",
        ]
        
        for ins in insights:
            icon = "🟢" if ins.trend == "UP" else "🔴" if ins.trend == "DOWN" else "🟡"
            content.append(f"- **{ins.asset.upper()}**: {icon} {ins.summary}")
            
        content.append("\n## 2. Market Snapshot")
        content.append("| Asset | Trend | Volatility | Drawdown | Regime |")
        content.append("|-------|-------|------------|----------|--------|")
        for ins in insights:
            content.append(f"| {ins.asset} | {ins.trend} | {ins.volatility_state} | {ins.drawdown_pct:.1%} | {ins.regime} |")  # noqa: E501
            
        content.append("\n## 3. ML Signals (Short-Term Direction)")
        content.append("| Asset | Model | Horizon | Prob(Up) | Signal | Confidence |")
        content.append("|-------|-------|---------|----------|--------|------------|")
        for p in predictions:
            conf_str = f"{p.confidence_score:.2f}"
            content.append(f"| {p.asset} | {p.model_name} | {p.horizon_days}d | {p.probability_up:.1%} | {p.signal} | {conf_str} |")  # noqa: E501
            
        content.append("\n## 4. Risk Notes")
        content.append("- **Model Uncertainty**: Probabilities near 50% indicate low conviction.")
        content.append("- **Regime Shifts**: High volatility environments degrade model performance.")
        content.append("- **Data Lag**: Analysis based on previous day close.")
        
        with open(filename, "w") as f:
            f.write("\n".join(content))
            
        return filename

    def generate_json(
        self, 
        insights: list[MarketInsight], 
        predictions: list[Prediction]
    ) -> Path:
        data = {
            "generated_at": datetime.now().isoformat(),
            "insights": [self._insight_to_dict(i) for i in insights],
            "predictions": [self._prediction_to_dict(p) for p in predictions]
        }
        
        filename = self.output_dir / "latest_metrics.json"
        with open(filename, "w") as f:
            json.dump(data, f, indent=2, default=str)
            
        return filename
        
    def _insight_to_dict(self, i: MarketInsight) -> dict:
        return {
            "asset": i.asset,
            "trend": i.trend,
            "volatility": i.volatility_state,
            "regime": i.regime,
            "drawdown": i.drawdown_pct,
            "summary": i.summary
        }

    def _prediction_to_dict(self, p: Prediction) -> dict:
        return {
            "asset": p.asset,
            "model": p.model_name,
            "prob_up": p.probability_up,
            "signal": p.signal,
            "confidence": p.confidence_score
        }
